// @takazudo/zudo-sg/islands — side-effect module that statically imports
// every engine island (ADR docs/adr/styleguide-engine.md finding 4,
// decision 7).
//
// Required on zfb < 2.18.0, where `zfb dev` seeded its island scanner from
// the host `pages/` root only; since 2.18.0 dev seeds the injected route
// entrypoints and resolves plugin virtual modules, so on the engine's peer
// floor this is a harmless no-op kept for API stability (ADR finding 4
// amendment). Hosts may still import it once from a `pages/` file
// (`pages/lib/_zudo-sg-islands.ts` = `import "@takazudo/zudo-sg/islands";`,
// imported by `pages/index.tsx`).
//
// Keep the list in sync with the `"use client"` components the route
// entrypoints mount. The `../routes-src/` escape is deliberate: the configured
// preview wrapper imports `virtual:zudo-sg-registry`, so it ships as route
// source next to the entrypoints, and the relative path resolves from
// `dist/islands.js` in the workspace and in the published tarball alike.

import "./preview/detail-workbench.js";
import "./code-panel/code-panel.js";
import "./search/catalog-filter.js";
import "./token-tweak/preview-tokens-button.js";
import "./token-tweak/preview-token-panel-bootstrap.js";
// @ts-ignore -- route source outside `src/`; generated by scripts/copy-routes-src.mjs, bundled by zfb.
import "../routes-src/_preview-app.tsx";
