// @takazudo/zudo-sg/islands — dev-hydration seed (ADR
// docs/adr/styleguide-engine.md finding 4, decision 7).
//
// `zfb dev` seeds its island scanner from the host `pages/` root ONLY — it
// never walks injected package routes — so an engine island reachable only
// through `routes-src/*.tsx` hydrates in `zfb build` but not in `zfb dev`.
// Hosts import this side-effect module once from a `pages/` file
// (`pages/lib/_zudo-sg-islands.ts` = `import "@takazudo/zudo-sg/islands";`,
// imported by `pages/index.tsx`), which puts every engine island into the
// site-wide island manifest. Harmless in `zfb build`: the same module reached
// through two graphs is deduped by path.
//
// Keep the list in sync with the `"use client"` components the route
// entrypoints mount. The `../routes-src/` escape is deliberate: the configured
// preview wrapper imports `virtual:zudo-sg-registry`, so it ships as route
// source next to the entrypoints, and the relative path resolves from
// `dist/islands.js` in the workspace and in the published tarball alike.

import "./preview/detail-workbench.js";
import "./code-panel/code-panel.js";
import "./search/catalog-filter.js";
import "./token-tweak/preview-tokens-button.js";
import "./token-tweak/preview-token-panel-bootstrap.js";
// @ts-ignore -- route source outside `src/`; generated by scripts/copy-routes-src.mjs, bundled by zfb.
import "../routes-src/_preview-app.tsx";
