// GENERATED by `zudo-sg gen-registry` — seed file. Run `pnpm gen-registry`
// after changing stories; the command rewrites the block below from
// ui/*.stories.tsx. This seed only needs the BEGIN/END markers present once.
// GENERATED:SG_REGISTRY_BEGIN — do not hand-edit; run `pnpm gen:sg-registry`.
import type { StoryModule } from "@takazudo/zudo-sg/stories";

import * as button from "../../ui/button/button.stories.tsx";
import * as card from "../../ui/card/card.stories.tsx";
import * as counter from "../../ui/counter/counter.stories.tsx";

/**
 * Path → story module map. Keys are glob-relative (e.g.
 * `./ui/src/button/button.stories.tsx`). Each module is
 * `{ default: meta, ...named Story exports }`.
 */
export const storyModules: Record<string, StoryModule> = {
  "./ui/button/button.stories.tsx": button as unknown as StoryModule,
  "./ui/card/card.stories.tsx": card as unknown as StoryModule,
  "./ui/counter/counter.stories.tsx": counter as unknown as StoryModule,
};

/**
 * Per-story named-export declaration order (SOURCE order), keyed by the
 * same path as `storyModules`. registry.ts sorts each story's variants
 * by this so tabs render in authored order (and the default tab is the
 * first-authored story) instead of the alphabetical key-enumeration order
 * of the `import * as` namespace. Captured at codegen time because the
 * runtime namespace cannot recover source order (#128 / #174). Superset:
 * lists every `export const`, so registry.ts uses it only to SORT the
 * `isStory()`-filtered variants, never to gate membership.
 */
export const storyExportOrder: Record<string, string[]> = {
  "./ui/button/button.stories.tsx": ["Primary", "Plain"],
  "./ui/card/card.stories.tsx": ["Basic"],
  "./ui/counter/counter.stories.tsx": ["Basic"],
};
// GENERATED:SG_REGISTRY_END
