// GENERATED by `zudo-sg gen-registry` — seed file. The verify script runs
// that command before every build, which rewrites the block below from
// ui/*.stories.tsx; this seed only needs the BEGIN/END markers present once.
// GENERATED:SG_REGISTRY_BEGIN — do not hand-edit; run `pnpm gen-registry`.
import type { StoryModule } from "@takazudo/zudo-sg/stories";

export const storyModules: Record<string, StoryModule> = {};

export const storyExportOrder: Record<string, string[]> = {};
// GENERATED:SG_REGISTRY_END
