// Generated by scripts/gen-composer-pack.mjs. Do not edit by hand.
import { defineComponentPack } from "@zudo-composer/component-contract";

import { calloutComposer as cardsCalloutCallout } from "./cards/callout/callout.composer";
import { cardComposer as cardsCardCard } from "./cards/card/card.composer";
import { proseMdComposer as contentProseMdProseMd } from "./content/prose-md/prose-md.composer";
import { prosePComposer as contentProsePProseP } from "./content/prose-p/prose-p.composer";
import { placeholderBoxComposer as mediaPlaceholderBoxPlaceholderBox } from "./media/placeholder-box/placeholder-box.composer";
import { autoGridComposer as sharedAutoGridAutoGrid } from "./shared/auto-grid/auto-grid.composer";
import { containerComposer as sharedContainerContainer } from "./shared/container/container.composer";
import { ctaButtonComposer as sharedCtaButtonCtaButton } from "./shared/cta-button/cta-button.composer";
import { heroComposer as sharedHeroHero } from "./shared/hero/hero.composer";
import { sectionHeadingComposer as sharedSectionHeadingSectionHeading } from "./shared/section-heading/section-heading.composer";
import { splitLayoutComposer as sharedSplitLayoutSplitLayout } from "./shared/split-layout/split-layout.composer";
import { stackComposer as sharedStackStack } from "./shared/stack/stack.composer";

export const componentPack = defineComponentPack({
  packId: "@zudo-sg/ui",
  packVersion: "1.0.0",
  components: [
    cardsCalloutCallout,
    cardsCardCard,
    contentProseMdProseMd,
    contentProsePProseP,
    mediaPlaceholderBoxPlaceholderBox,
    sharedAutoGridAutoGrid,
    sharedContainerContainer,
    sharedCtaButtonCtaButton,
    sharedHeroHero,
    sharedSectionHeadingSectionHeading,
    sharedSplitLayoutSplitLayout,
    sharedStackStack,
  ],
});

export const componentPackManifest = componentPack.manifest;
export const componentRuntimeRegistry = componentPack.runtime;
