// GENERATED by `zudo-sg gen-registry` — seed file. Run `pnpm gen-registry`
// after changing stories; the command rewrites the block below from
// ui/*.stories.tsx. This seed only needs the BEGIN/END markers present once.
// GENERATED:SG_REGISTRY_BEGIN — do not hand-edit; run `pnpm gen-registry`.
import type { StoryModule } from "@takazudo/zudo-sg/stories";

export const storyModules: Record<string, StoryModule> = {};

export const storyExportOrder: Record<string, string[]> = {};
// GENERATED:SG_REGISTRY_END
