// Re-export shared settings types from zudo-doc.
export type {
  TagGovernanceMode,
  TagVocabularyEntry,
  HeaderNavChildItem,
  HeaderNavItem,
  HeaderRightComponentName,
  HeaderRightComponentItem,
  HeaderRightLinkItem,
  HeaderRightHtmlItem,
  HeaderRightItem,
  BodyFootUtilAreaConfig,
  ColorModeConfig,
  LocaleConfig,
  FooterLinkItem,
  FooterLinkColumn,
  FooterTaglistLocaleConfig,
  FooterTaglistConfig,
  FooterConfig,
  HtmlPreviewConfig,
  FrontmatterPreviewConfig,
  TagPlacement,
  VersionConfig,
  ChangelogConfig,
  MetaTagsConfig,
  SiteHeadConfig,
  Settings,
} from "@takazudo/zudo-doc/settings";
