// Ambient declarations for the virtual modules registered by
// `@takazudo/zudo-sg/plugins/routes`. Source of truth for the shipped
// package-root `virtual-modules.d.ts` (generated by
// scripts/copy-virtual-modules.mjs, which rewrites the parent-relative
// `import(...)` specifiers below to bare `@takazudo/zudo-sg/*` subpaths).
// Only inline `import(...)` types are allowed here — a top-level import would
// turn the ambient blocks into module augmentations.

declare module "virtual:zudo-sg-context" {
  export const sgContext: import("../sg-context.js").SgContext;
}

declare module "virtual:zudo-sg-registry" {
  export const storyModules: Record<string, import("../stories/index.js").StoryModule>;
  export const storyExportOrder: Record<string, string[]>;
}

declare module "virtual:zudo-sg-tokens" {
  export const tokensManifest: import("../token-dashboard/index.js").UiDesignTokensManifest | null;
}
