/**
 * Composer/styleguide icon set — renderer-safe: plain `.ts` + Preact `h()`,
 * NO JSX. The composer preview iframe bundle is deliberately JSX-free (see the
 * header of `src/features/composer/preview/preview-app.ts`: root-`src` `.tsx`
 * modules cannot be imported under the shared vitest config), and this module
 * must import cleanly from BOTH the host chrome and that preview bundle — so
 * it stays `h()`-based.
 *
 * Pattern ported from zudo-text (`packages/ui-components/src/icons.tsx`):
 * `makeIcon(renderSvg, defaultSize)` produces a named-export icon component.
 * Every icon: 16 viewBox, `currentColor` fill/stroke only (never hardcoded
 * hex), `aria-hidden="true"`, flat/line style, stroke-width 1.25–2.5.
 *
 * Sizing: the `size` prop (`xs|sm|md|lg`) maps to `w-icon-*` / `h-icon-*`
 * utilities, generated by Tailwind v4 from the `--spacing-icon-*` tokens in
 * `src/styles/global.css` (12/16/20/24px). Explicit `width`/`height` props
 * bypass the wrapper span and size the `<svg>` directly.
 *
 * ── Icon → composer usage map (glyph-swap guide for the A6 host chrome and
 *    A7 preview-iframe subs, #279) ─────────────────────────────────────────
 *
 * | Icon             | Composer surface(s)                                        |
 * | ---------------- | ---------------------------------------------------------- |
 * | ChevronRightIcon | Tree disclosure — collapsed row                            |
 * | ChevronDownIcon  | Tree disclosure — expanded row; inspector "move down"      |
 * | ChevronUpIcon    | Inspector "move up"                                        |
 * | EllipsisIcon     | Menu triggers — tree-row / node overflow kebab             |
 * | XMarkIcon        | Tree row remove; dialog close                              |
 * | PlusIcon         | Add affordances (insert buttons); "Add"/insert menu items  |
 * | CopyIcon         | Clipboard chip; "Copy" menu item                           |
 * | CutIcon          | "Cut" menu item                                            |
 * | DuplicateIcon    | Duplicate action — inspector button; "Duplicate" menu item |
 * | TrashIcon        | Delete action — inspector button; "Delete" menu item       |
 * | DragGripIcon     | Tree row drag handle                                       |
 * | ExpandIcon       | Component-chooser enlarge                                  |
 * | PageIcon         | Tree node-type glyph: page / root                          |
 * | SlotIcon         | Tree node-type glyph: slot                                 |
 * | ContainerIcon    | Tree node-type glyph: container                            |
 * | LeafIcon         | Tree node-type glyph: leaf component                       |
 */

import { h } from "preact";
import type { FunctionComponent, JSX, VNode } from "preact";

export type IconSize = "xs" | "sm" | "md" | "lg";

export interface IconProps {
  /** Explicit pixel width — bypasses the size-class wrapper span. */
  width?: number;
  /** Explicit pixel height — bypasses the size-class wrapper span. */
  height?: number;
  /** Token-driven size (default `"md"`), via `w-icon-*` / `h-icon-*`. */
  size?: IconSize;
  class?: string;
  style?: string | JSX.CSSProperties;
}

export type IconComponent = FunctionComponent<IconProps>;

// Preact's `VNode<P>` is invariant in `P` (its `type` field is a
// contravariant `ComponentType<P>`), so a `VNode<{ d: string }>` from
// `h("path", …)` is NOT assignable to the default `VNode<{}>` — the internal
// signatures use this erased alias instead.
type AnyVNode = VNode<any>;

const sizeClasses: Record<IconSize, string> = {
  xs: "w-icon-xs h-icon-xs",
  sm: "w-icon-sm h-icon-sm",
  md: "w-icon-md h-icon-md",
  lg: "w-icon-lg h-icon-lg",
};

type IconRenderFn = (
  width: number | string,
  height: number | string,
  cls: string | undefined,
  style: string | JSX.CSSProperties | undefined,
) => AnyVNode;

/**
 * Factory that produces an `XxxIcon` component from a single SVG render
 * function (zudo-text pattern).
 *
 * - Explicit-size branch (`width`/`height` prop given): delegates directly to
 *   `renderSvg` with the numeric dimensions, `class`, and `style`.
 * - Default branch: wraps `renderSvg("100%", "100%", …)` in a flex `<span>`
 *   that carries the size class, `class`, and `style`.
 *
 * `defaultSize` fills in the other dimension when only one of
 * `width`/`height` is supplied.
 */
function makeIcon(renderSvg: IconRenderFn, defaultSize = 16): IconComponent {
  return function Icon({ width, height, size = "md", class: cls, style }: IconProps): AnyVNode {
    if (width !== undefined || height !== undefined) {
      return renderSvg(width ?? defaultSize, height ?? defaultSize, cls, style);
    }
    return h(
      "span",
      {
        class: `inline-flex items-center justify-center shrink-0 ${sizeClasses[size]}${cls ? ` ${cls}` : ""}`,
        style,
      },
      renderSvg("100%", "100%", undefined, undefined),
    );
  };
}

type SvgChildProps = Record<string, string | number>;

/** Shared `<svg>` shell: 16 viewBox, `aria-hidden`, per-icon paint props. */
function svgRoot(
  width: number | string,
  height: number | string,
  cls: string | undefined,
  style: string | JSX.CSSProperties | undefined,
  paint: SvgChildProps,
  children: AnyVNode[],
): AnyVNode {
  return h(
    "svg",
    {
      "aria-hidden": "true",
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 16 16",
      width,
      height,
      class: cls,
      style,
      ...paint,
    },
    children,
  );
}

const FILLED: SvgChildProps = { fill: "currentColor" };

function stroked(strokeWidth: number): SvgChildProps {
  return {
    fill: "none",
    stroke: "currentColor",
    "stroke-width": strokeWidth,
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
  };
}

function evenOddPath(d: string): AnyVNode {
  return h("path", { "fill-rule": "evenodd", "clip-rule": "evenodd", d });
}

// ── Chevrons (ported from zudo-text) ─────────────────────────────────────────

export const ChevronRightIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M6.22 4.22a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06l-3.25 3.25a.75.75 0 0 1-1.06-1.06L8.94 8 6.22 5.28a.75.75 0 0 1 0-1.06Z",
    ),
  ]),
);

export const ChevronDownIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z",
    ),
  ]),
);

export const ChevronUpIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M11.78 9.78a.75.75 0 0 1-1.06 0L8 7.06 5.28 9.78a.75.75 0 0 1-1.06-1.06l3.25-3.25a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06Z",
    ),
  ]),
);

// ── Actions (ported from zudo-text) ──────────────────────────────────────────

export const PlusIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    h("path", {
      d: "M8 2a.75.75 0 0 1 .75.75v4.5h4.5a.75.75 0 0 1 0 1.5h-4.5v4.5a.75.75 0 0 1-1.5 0v-4.5h-4.5a.75.75 0 0 1 0-1.5h4.5v-4.5A.75.75 0 0 1 8 2Z",
    }),
  ]),
);

export const XMarkIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M4.28 3.22a.75.75 0 0 0-1.06 1.06L6.94 8l-3.72 3.72a.75.75 0 1 0 1.06 1.06L8 9.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L9.06 8l3.72-3.72a.75.75 0 0 0-1.06-1.06L8 6.94 4.28 3.22Z",
    ),
  ]),
);

export const TrashIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M5 3.25V4H2.75a.75.75 0 0 0 0 1.5h.3l.815 8.15A1.5 1.5 0 0 0 5.357 15h5.285a1.5 1.5 0 0 0 1.493-1.35l.815-8.15h.3a.75.75 0 0 0 0-1.5H11v-.75A2.25 2.25 0 0 0 8.75 1h-1.5A2.25 2.25 0 0 0 5 3.25Zm2.25-.75a.75.75 0 0 0-.75.75V4h3v-.75a.75.75 0 0 0-.75-.75h-1.5ZM6.05 6a.75.75 0 0 1 .787.713l.275 5.5a.75.75 0 0 1-1.498.075l-.275-5.5A.75.75 0 0 1 6.05 6Zm3.9 0a.75.75 0 0 1 .712.787l-.275 5.5a.75.75 0 0 1-1.498-.075l.275-5.5a.75.75 0 0 1 .786-.712Z",
    ),
  ]),
);

/** Corner brackets pointing outward — zudo-text's `ArrowsPointingOutIcon`. */
export const ExpandIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    evenOddPath(
      "M2.75 2a.75.75 0 0 0-.75.75v2.5a.75.75 0 0 0 1.5 0V3.5h1.75a.75.75 0 0 0 0-1.5h-2.5ZM10.75 2a.75.75 0 0 0 0 1.5h1.75v1.75a.75.75 0 0 0 1.5 0v-2.5a.75.75 0 0 0-.75-.75h-2.5ZM3.5 10.75a.75.75 0 0 0-1.5 0v2.5c0 .414.336.75.75.75h2.5a.75.75 0 0 0 0-1.5H3.5v-1.75ZM12.5 10.75a.75.75 0 0 1 1.5 0v2.5a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1 0-1.5h1.75v-1.75Z",
    ),
  ]),
);

// ── Actions (authored new, matching the zudo-text flat/line weight) ──────────

/** Vertical kebab dots — the overflow-menu trigger glyph. */
export const EllipsisIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    h("circle", { cx: 8, cy: 3.25, r: 1.4 }),
    h("circle", { cx: 8, cy: 8, r: 1.4 }),
    h("circle", { cx: 8, cy: 12.75, r: 1.4 }),
  ]),
);

/** Two offset pages — the clipboard "copy" glyph. */
export const CopyIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("rect", { x: 5.5, y: 5.5, width: 8.5, height: 8.5, rx: 1.25 }),
    h("path", {
      d: "M3.25 10.75h-.5c-.83 0-1.5-.67-1.5-1.5v-6c0-.83.67-1.5 1.5-1.5h6c.83 0 1.5.67 1.5 1.5v.5",
    }),
  ]),
);

/** Scissors — the clipboard "cut" glyph. */
export const CutIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("circle", { cx: 4, cy: 4, r: 2.1 }),
    h("circle", { cx: 4, cy: 12, r: 2.1 }),
    h("line", { x1: 13.5, y1: 2.5, x2: 5.5, y2: 10.5 }),
    h("line", { x1: 9.7, y1: 9.7, x2: 13.5, y2: 13.5 }),
    h("line", { x1: 5.5, y1: 5.5, x2: 8.1, y2: 8.1 }),
  ]),
);

/** Copy pages with a plus badge — "duplicate in place", distinct from Copy. */
export const DuplicateIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("rect", { x: 5.5, y: 5.5, width: 8.5, height: 8.5, rx: 1.25 }),
    h("path", {
      d: "M3.25 10.75h-.5c-.83 0-1.5-.67-1.5-1.5v-6c0-.83.67-1.5 1.5-1.5h6c.83 0 1.5.67 1.5 1.5v.5",
    }),
    h("line", { x1: 9.75, y1: 8, x2: 9.75, y2: 11.5 }),
    h("line", { x1: 8, y1: 9.75, x2: 11.5, y2: 9.75 }),
  ]),
);

/** Six-dot grip (2×3) — the drag-handle glyph. */
export const DragGripIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    h("circle", { cx: 5.5, cy: 3.5, r: 1.2 }),
    h("circle", { cx: 10.5, cy: 3.5, r: 1.2 }),
    h("circle", { cx: 5.5, cy: 8, r: 1.2 }),
    h("circle", { cx: 10.5, cy: 8, r: 1.2 }),
    h("circle", { cx: 5.5, cy: 12.5, r: 1.2 }),
    h("circle", { cx: 10.5, cy: 12.5, r: 1.2 }),
  ]),
);

// ── Tree node-type glyphs (authored new; render down to 12px / size "xs") ────

/** Page/root node: framed page with a header rule. */
export const PageIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("rect", { x: 1.75, y: 2.25, width: 12.5, height: 11.5, rx: 1.25 }),
    h("line", { x1: 1.75, y1: 5.25, x2: 14.25, y2: 5.25 }),
  ]),
);

/** Slot node: dashed outline — an insertion placeholder awaiting content. */
export const SlotIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("rect", { x: 2.25, y: 2.25, width: 11.5, height: 11.5, rx: 1.5, "stroke-dasharray": "2.5 2" }),
  ]),
);

/** Container node: solid box holding stacked child rows. */
export const ContainerIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, stroked(1.5), [
    h("rect", { x: 2, y: 2, width: 12, height: 12, rx: 1.5 }),
    h("line", { x1: 4.75, y1: 6.25, x2: 11.25, y2: 6.25 }),
    h("line", { x1: 4.75, y1: 9.75, x2: 11.25, y2: 9.75 }),
  ]),
);

/** Leaf node: small solid block — the atomic, terminal component. */
export const LeafIcon: IconComponent = makeIcon((w, hgt, cls, style) =>
  svgRoot(w, hgt, cls, style, FILLED, [
    h("rect", { x: 4.5, y: 4.5, width: 7, height: 7, rx: 1.75 }),
  ]),
);
